language: node_js
node_js:
- "stable"

services: mongodb

before_script:
  - node server.js &
  - sleep 3 # give server some time to start
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - npm test
