export { AlertService } from './alert.service';
export { AuthenticationService } from './authentication.service';
export { UserService } from './user.service';
export { NewsService } from './news.service';
export { NewsHeaderService } from './newsheader.service';
export { CarouselService } from './carousel.service';
export { FeaturetteService } from './featurette.service';
export { CalendarService } from './calendar.service';
export { AboutPageService } from './about-page.service';
export { ContactPageService } from './contact-page.service';
export { BrancaService } from './branca.service';
export { DownloadService } from './download.service';
export { AppConfigService } from './app-config.service';
export { CustomPageService} from './custom-page.service';
