export { User }  from './user.model';
export { Event }  from './event.model';
export { AboutPage } from './about-page.model';
export { ContactPage } from './contact-page.model';
export { Contact } from './contact.model';
export { DTCarousel } from './dt-carousel.model';
export { Featurette } from './featurette.model';
export { News } from './news.model';
export { Branca } from './branca.model';
export {CustomPage} from './custom-page.model';
